/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables.records;


import my.playground.orm.thirdtry.tables.Ent3;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Ent3Record extends UpdatableRecordImpl<Ent3Record> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Ent3.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Ent3.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ent3.ENT3.ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Ent3Record value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public Ent3Record values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Ent3Record
     */
    public Ent3Record() {
        super(Ent3.ENT3);
    }

    /**
     * Create a detached, initialised Ent3Record
     */
    public Ent3Record(Integer id) {
        super(Ent3.ENT3);

        setId(id);
    }
}
