/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables.records;


import my.playground.orm.thirdtry.tables.Jointableinheritor;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class JointableinheritorRecord extends UpdatableRecordImpl<JointableinheritorRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>JoinTableInheritor.inheritorValue</code>.
     */
    public void setInheritorvalue(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>JoinTableInheritor.inheritorValue</code>.
     */
    public String getInheritorvalue() {
        return (String) get(0);
    }

    /**
     * Setter for <code>JoinTableInheritor.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>JoinTableInheritor.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Jointableinheritor.JOINTABLEINHERITOR.INHERITORVALUE;
    }

    @Override
    public Field<Long> field2() {
        return Jointableinheritor.JOINTABLEINHERITOR.ID;
    }

    @Override
    public String component1() {
        return getInheritorvalue();
    }

    @Override
    public Long component2() {
        return getId();
    }

    @Override
    public String value1() {
        return getInheritorvalue();
    }

    @Override
    public Long value2() {
        return getId();
    }

    @Override
    public JointableinheritorRecord value1(String value) {
        setInheritorvalue(value);
        return this;
    }

    @Override
    public JointableinheritorRecord value2(Long value) {
        setId(value);
        return this;
    }

    @Override
    public JointableinheritorRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JointableinheritorRecord
     */
    public JointableinheritorRecord() {
        super(Jointableinheritor.JOINTABLEINHERITOR);
    }

    /**
     * Create a detached, initialised JointableinheritorRecord
     */
    public JointableinheritorRecord(String inheritorvalue, Long id) {
        super(Jointableinheritor.JOINTABLEINHERITOR);

        setInheritorvalue(inheritorvalue);
        setId(id);
    }
}
