/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables.records;


import my.playground.orm.thirdtry.tables.MappedEmailEager;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MappedEmailEagerRecord extends UpdatableRecordImpl<MappedEmailEagerRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mapped_email_eager.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mapped_email_eager.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MappedEmailEager.MAPPED_EMAIL_EAGER.ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public MappedEmailEagerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MappedEmailEagerRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MappedEmailEagerRecord
     */
    public MappedEmailEagerRecord() {
        super(MappedEmailEager.MAPPED_EMAIL_EAGER);
    }

    /**
     * Create a detached, initialised MappedEmailEagerRecord
     */
    public MappedEmailEagerRecord(Integer id) {
        super(MappedEmailEager.MAPPED_EMAIL_EAGER);

        setId(id);
    }
}
