/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables.records;


import my.playground.orm.thirdtry.tables.MappedEmail;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MappedEmailRecord extends UpdatableRecordImpl<MappedEmailRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mapped_email.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mapped_email.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mapped_email.subject</code>.
     */
    public void setSubject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mapped_email.subject</code>.
     */
    public String getSubject() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MappedEmail.MAPPED_EMAIL.ID;
    }

    @Override
    public Field<String> field2() {
        return MappedEmail.MAPPED_EMAIL.SUBJECT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public MappedEmailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MappedEmailRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public MappedEmailRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MappedEmailRecord
     */
    public MappedEmailRecord() {
        super(MappedEmail.MAPPED_EMAIL);
    }

    /**
     * Create a detached, initialised MappedEmailRecord
     */
    public MappedEmailRecord(Integer id, String subject) {
        super(MappedEmail.MAPPED_EMAIL);

        setId(id);
        setSubject(subject);
    }
}
