/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables.records;


import my.playground.orm.thirdtry.tables.NonMappedEmail;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NonMappedEmailRecord extends UpdatableRecordImpl<NonMappedEmailRecord> implements Record3<Integer, String, byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>non_mapped_email.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>non_mapped_email.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>non_mapped_email.subject</code>.
     */
    public void setSubject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>non_mapped_email.subject</code>.
     */
    public String getSubject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>non_mapped_email.message_id</code>.
     */
    public void setMessageId(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>non_mapped_email.message_id</code>.
     */
    public byte[] getMessageId() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, byte[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NonMappedEmail.NON_MAPPED_EMAIL.ID;
    }

    @Override
    public Field<String> field2() {
        return NonMappedEmail.NON_MAPPED_EMAIL.SUBJECT;
    }

    @Override
    public Field<byte[]> field3() {
        return NonMappedEmail.NON_MAPPED_EMAIL.MESSAGE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public byte[] component3() {
        return getMessageId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public byte[] value3() {
        return getMessageId();
    }

    @Override
    public NonMappedEmailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NonMappedEmailRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public NonMappedEmailRecord value3(byte[] value) {
        setMessageId(value);
        return this;
    }

    @Override
    public NonMappedEmailRecord values(Integer value1, String value2, byte[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NonMappedEmailRecord
     */
    public NonMappedEmailRecord() {
        super(NonMappedEmail.NON_MAPPED_EMAIL);
    }

    /**
     * Create a detached, initialised NonMappedEmailRecord
     */
    public NonMappedEmailRecord(Integer id, String subject, byte[] messageId) {
        super(NonMappedEmail.NON_MAPPED_EMAIL);

        setId(id);
        setSubject(subject);
        setMessageId(messageId);
    }
}
