/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables.records;


import my.playground.orm.thirdtry.tables.Separatetableinheritor;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SeparatetableinheritorRecord extends UpdatableRecordImpl<SeparatetableinheritorRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SeparateTableInheritor.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SeparateTableInheritor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SeparateTableInheritor.parentData</code>.
     */
    public void setParentdata(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SeparateTableInheritor.parentData</code>.
     */
    public String getParentdata() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SeparateTableInheritor.inheritorValue</code>.
     */
    public void setInheritorvalue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SeparateTableInheritor.inheritorValue</code>.
     */
    public String getInheritorvalue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Separatetableinheritor.SEPARATETABLEINHERITOR.ID;
    }

    @Override
    public Field<String> field2() {
        return Separatetableinheritor.SEPARATETABLEINHERITOR.PARENTDATA;
    }

    @Override
    public Field<String> field3() {
        return Separatetableinheritor.SEPARATETABLEINHERITOR.INHERITORVALUE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getParentdata();
    }

    @Override
    public String component3() {
        return getInheritorvalue();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getParentdata();
    }

    @Override
    public String value3() {
        return getInheritorvalue();
    }

    @Override
    public SeparatetableinheritorRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SeparatetableinheritorRecord value2(String value) {
        setParentdata(value);
        return this;
    }

    @Override
    public SeparatetableinheritorRecord value3(String value) {
        setInheritorvalue(value);
        return this;
    }

    @Override
    public SeparatetableinheritorRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeparatetableinheritorRecord
     */
    public SeparatetableinheritorRecord() {
        super(Separatetableinheritor.SEPARATETABLEINHERITOR);
    }

    /**
     * Create a detached, initialised SeparatetableinheritorRecord
     */
    public SeparatetableinheritorRecord(Long id, String parentdata, String inheritorvalue) {
        super(Separatetableinheritor.SEPARATETABLEINHERITOR);

        setId(id);
        setParentdata(parentdata);
        setInheritorvalue(inheritorvalue);
    }
}
