/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.jooq;


import my.playground.orm.thirdtry.jooq.tables.Author;
import my.playground.orm.thirdtry.jooq.tables.records.AuthorRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * LIBRARY.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> SYS_PK_10206 = Internal.createUniqueKey(Author.AUTHOR, DSL.name("SYS_PK_10206"), new TableField[] { Author.AUTHOR.ID }, true);
}
