/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.jooq;


import java.util.Arrays;
import java.util.List;

import my.playground.orm.thirdtry.jooq.tables.Author;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Library extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LIBRARY</code>
     */
    public static final Library LIBRARY = new Library();

    /**
     * The table <code>LIBRARY.AUTHOR</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * No further instances allowed
     */
    private Library() {
        super("LIBRARY", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR
        );
    }
}
