/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.jooq;


import my.playground.orm.thirdtry.jooq.tables.Author;


/**
 * Convenience access to all tables in LIBRARY.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>LIBRARY.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
