/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.Ent1Record;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Ent1 extends TableImpl<Ent1Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Ent1</code>
     */
    public static final Ent1 ENT1 = new Ent1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Ent1Record> getRecordType() {
        return Ent1Record.class;
    }

    /**
     * The column <code>Ent1.id</code>.
     */
    public final TableField<Ent1Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Ent1.ent3_id</code>.
     */
    public final TableField<Ent1Record, Integer> ENT3_ID = createField(DSL.name("ent3_id"), SQLDataType.INTEGER, this, "");

    private Ent1(Name alias, Table<Ent1Record> aliased) {
        this(alias, aliased, null);
    }

    private Ent1(Name alias, Table<Ent1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Ent1</code> table reference
     */
    public Ent1(String alias) {
        this(DSL.name(alias), ENT1);
    }

    /**
     * Create an aliased <code>Ent1</code> table reference
     */
    public Ent1(Name alias) {
        this(alias, ENT1);
    }

    /**
     * Create a <code>Ent1</code> table reference
     */
    public Ent1() {
        this(DSL.name("Ent1"), null);
    }

    public <O extends Record> Ent1(Table<O> child, ForeignKey<O, Ent1Record> key) {
        super(child, key, ENT1);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Ent1Record> getPrimaryKey() {
        return Keys.ENT1__;
    }

    @Override
    public Ent1 as(String alias) {
        return new Ent1(DSL.name(alias), this);
    }

    @Override
    public Ent1 as(Name alias) {
        return new Ent1(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent1 rename(String name) {
        return new Ent1(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent1 rename(Name name) {
        return new Ent1(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
