/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.Ent1SeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Ent1Seq extends TableImpl<Ent1SeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Ent1_SEQ</code>
     */
    public static final Ent1Seq ENT1_SEQ = new Ent1Seq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Ent1SeqRecord> getRecordType() {
        return Ent1SeqRecord.class;
    }

    /**
     * The column <code>Ent1_SEQ.next_val</code>.
     */
    public final TableField<Ent1SeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private Ent1Seq(Name alias, Table<Ent1SeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ent1Seq(Name alias, Table<Ent1SeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Ent1_SEQ</code> table reference
     */
    public Ent1Seq(String alias) {
        this(DSL.name(alias), ENT1_SEQ);
    }

    /**
     * Create an aliased <code>Ent1_SEQ</code> table reference
     */
    public Ent1Seq(Name alias) {
        this(alias, ENT1_SEQ);
    }

    /**
     * Create a <code>Ent1_SEQ</code> table reference
     */
    public Ent1Seq() {
        this(DSL.name("Ent1_SEQ"), null);
    }

    public <O extends Record> Ent1Seq(Table<O> child, ForeignKey<O, Ent1SeqRecord> key) {
        super(child, key, ENT1_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Ent1Seq as(String alias) {
        return new Ent1Seq(DSL.name(alias), this);
    }

    @Override
    public Ent1Seq as(Name alias) {
        return new Ent1Seq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent1Seq rename(String name) {
        return new Ent1Seq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent1Seq rename(Name name) {
        return new Ent1Seq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
