/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.Ent2SeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Ent2Seq extends TableImpl<Ent2SeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Ent2_SEQ</code>
     */
    public static final Ent2Seq ENT2_SEQ = new Ent2Seq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Ent2SeqRecord> getRecordType() {
        return Ent2SeqRecord.class;
    }

    /**
     * The column <code>Ent2_SEQ.next_val</code>.
     */
    public final TableField<Ent2SeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private Ent2Seq(Name alias, Table<Ent2SeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ent2Seq(Name alias, Table<Ent2SeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Ent2_SEQ</code> table reference
     */
    public Ent2Seq(String alias) {
        this(DSL.name(alias), ENT2_SEQ);
    }

    /**
     * Create an aliased <code>Ent2_SEQ</code> table reference
     */
    public Ent2Seq(Name alias) {
        this(alias, ENT2_SEQ);
    }

    /**
     * Create a <code>Ent2_SEQ</code> table reference
     */
    public Ent2Seq() {
        this(DSL.name("Ent2_SEQ"), null);
    }

    public <O extends Record> Ent2Seq(Table<O> child, ForeignKey<O, Ent2SeqRecord> key) {
        super(child, key, ENT2_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Ent2Seq as(String alias) {
        return new Ent2Seq(DSL.name(alias), this);
    }

    @Override
    public Ent2Seq as(Name alias) {
        return new Ent2Seq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent2Seq rename(String name) {
        return new Ent2Seq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent2Seq rename(Name name) {
        return new Ent2Seq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
