/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.Ent3Record;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Ent3 extends TableImpl<Ent3Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Ent3</code>
     */
    public static final Ent3 ENT3 = new Ent3();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Ent3Record> getRecordType() {
        return Ent3Record.class;
    }

    /**
     * The column <code>Ent3.id</code>.
     */
    public final TableField<Ent3Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Ent3(Name alias, Table<Ent3Record> aliased) {
        this(alias, aliased, null);
    }

    private Ent3(Name alias, Table<Ent3Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Ent3</code> table reference
     */
    public Ent3(String alias) {
        this(DSL.name(alias), ENT3);
    }

    /**
     * Create an aliased <code>Ent3</code> table reference
     */
    public Ent3(Name alias) {
        this(alias, ENT3);
    }

    /**
     * Create a <code>Ent3</code> table reference
     */
    public Ent3() {
        this(DSL.name("Ent3"), null);
    }

    public <O extends Record> Ent3(Table<O> child, ForeignKey<O, Ent3Record> key) {
        super(child, key, ENT3);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Ent3Record> getPrimaryKey() {
        return Keys.ENT3__;
    }

    @Override
    public Ent3 as(String alias) {
        return new Ent3(DSL.name(alias), this);
    }

    @Override
    public Ent3 as(Name alias) {
        return new Ent3(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent3 rename(String name) {
        return new Ent3(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent3 rename(Name name) {
        return new Ent3(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
