/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.Ent3SeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Ent3Seq extends TableImpl<Ent3SeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Ent3_SEQ</code>
     */
    public static final Ent3Seq ENT3_SEQ = new Ent3Seq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Ent3SeqRecord> getRecordType() {
        return Ent3SeqRecord.class;
    }

    /**
     * The column <code>Ent3_SEQ.next_val</code>.
     */
    public final TableField<Ent3SeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private Ent3Seq(Name alias, Table<Ent3SeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ent3Seq(Name alias, Table<Ent3SeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Ent3_SEQ</code> table reference
     */
    public Ent3Seq(String alias) {
        this(DSL.name(alias), ENT3_SEQ);
    }

    /**
     * Create an aliased <code>Ent3_SEQ</code> table reference
     */
    public Ent3Seq(Name alias) {
        this(alias, ENT3_SEQ);
    }

    /**
     * Create a <code>Ent3_SEQ</code> table reference
     */
    public Ent3Seq() {
        this(DSL.name("Ent3_SEQ"), null);
    }

    public <O extends Record> Ent3Seq(Table<O> child, ForeignKey<O, Ent3SeqRecord> key) {
        super(child, key, ENT3_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Ent3Seq as(String alias) {
        return new Ent3Seq(DSL.name(alias), this);
    }

    @Override
    public Ent3Seq as(Name alias) {
        return new Ent3Seq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent3Seq rename(String name) {
        return new Ent3Seq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ent3Seq rename(Name name) {
        return new Ent3Seq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
