/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.JointableinheritorRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Jointableinheritor extends TableImpl<JointableinheritorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>JoinTableInheritor</code>
     */
    public static final Jointableinheritor JOINTABLEINHERITOR = new Jointableinheritor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JointableinheritorRecord> getRecordType() {
        return JointableinheritorRecord.class;
    }

    /**
     * The column <code>JoinTableInheritor.inheritorValue</code>.
     */
    public final TableField<JointableinheritorRecord, String> INHERITORVALUE = createField(DSL.name("inheritorValue"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>JoinTableInheritor.id</code>.
     */
    public final TableField<JointableinheritorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Jointableinheritor(Name alias, Table<JointableinheritorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Jointableinheritor(Name alias, Table<JointableinheritorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>JoinTableInheritor</code> table reference
     */
    public Jointableinheritor(String alias) {
        this(DSL.name(alias), JOINTABLEINHERITOR);
    }

    /**
     * Create an aliased <code>JoinTableInheritor</code> table reference
     */
    public Jointableinheritor(Name alias) {
        this(alias, JOINTABLEINHERITOR);
    }

    /**
     * Create a <code>JoinTableInheritor</code> table reference
     */
    public Jointableinheritor() {
        this(DSL.name("JoinTableInheritor"), null);
    }

    public <O extends Record> Jointableinheritor(Table<O> child, ForeignKey<O, JointableinheritorRecord> key) {
        super(child, key, JOINTABLEINHERITOR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<JointableinheritorRecord> getPrimaryKey() {
        return Keys.JOINTABLEINHERITOR__;
    }

    @Override
    public Jointableinheritor as(String alias) {
        return new Jointableinheritor(DSL.name(alias), this);
    }

    @Override
    public Jointableinheritor as(Name alias) {
        return new Jointableinheritor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Jointableinheritor rename(String name) {
        return new Jointableinheritor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Jointableinheritor rename(Name name) {
        return new Jointableinheritor(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
