/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.MappedMessageRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MappedMessage extends TableImpl<MappedMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mapped_message</code>
     */
    public static final MappedMessage MAPPED_MESSAGE = new MappedMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MappedMessageRecord> getRecordType() {
        return MappedMessageRecord.class;
    }

    /**
     * The column <code>mapped_message.id</code>.
     */
    public final TableField<MappedMessageRecord, byte[]> ID = createField(DSL.name("id"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>mapped_message.content</code>.
     */
    public final TableField<MappedMessageRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>mapped_message.email_id</code>.
     */
    public final TableField<MappedMessageRecord, Long> EMAIL_ID = createField(DSL.name("email_id"), SQLDataType.BIGINT, this, "");

    private MappedMessage(Name alias, Table<MappedMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private MappedMessage(Name alias, Table<MappedMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mapped_message</code> table reference
     */
    public MappedMessage(String alias) {
        this(DSL.name(alias), MAPPED_MESSAGE);
    }

    /**
     * Create an aliased <code>mapped_message</code> table reference
     */
    public MappedMessage(Name alias) {
        this(alias, MAPPED_MESSAGE);
    }

    /**
     * Create a <code>mapped_message</code> table reference
     */
    public MappedMessage() {
        this(DSL.name("mapped_message"), null);
    }

    public <O extends Record> MappedMessage(Table<O> child, ForeignKey<O, MappedMessageRecord> key) {
        super(child, key, MAPPED_MESSAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<MappedMessageRecord> getPrimaryKey() {
        return Keys.MAPPED_MESSAGE__;
    }

    @Override
    public MappedMessage as(String alias) {
        return new MappedMessage(DSL.name(alias), this);
    }

    @Override
    public MappedMessage as(Name alias) {
        return new MappedMessage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MappedMessage rename(String name) {
        return new MappedMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MappedMessage rename(Name name) {
        return new MappedMessage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<byte[], String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
