/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.MappedEmailSubjectRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MappedEmailSubject extends TableImpl<MappedEmailSubjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mapped_email_subject</code>
     */
    public static final MappedEmailSubject MAPPED_EMAIL_SUBJECT = new MappedEmailSubject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MappedEmailSubjectRecord> getRecordType() {
        return MappedEmailSubjectRecord.class;
    }

    /**
     * The column <code>mapped_email_subject.subject</code>.
     */
    public final TableField<MappedEmailSubjectRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>mapped_email_subject.id</code>.
     */
    public final TableField<MappedEmailSubjectRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    private MappedEmailSubject(Name alias, Table<MappedEmailSubjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private MappedEmailSubject(Name alias, Table<MappedEmailSubjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mapped_email_subject</code> table reference
     */
    public MappedEmailSubject(String alias) {
        this(DSL.name(alias), MAPPED_EMAIL_SUBJECT);
    }

    /**
     * Create an aliased <code>mapped_email_subject</code> table reference
     */
    public MappedEmailSubject(Name alias) {
        this(alias, MAPPED_EMAIL_SUBJECT);
    }

    /**
     * Create a <code>mapped_email_subject</code> table reference
     */
    public MappedEmailSubject() {
        this(DSL.name("mapped_email_subject"), null);
    }

    public <O extends Record> MappedEmailSubject(Table<O> child, ForeignKey<O, MappedEmailSubjectRecord> key) {
        super(child, key, MAPPED_EMAIL_SUBJECT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<MappedEmailSubjectRecord> getPrimaryKey() {
        return Keys.MAPPED_EMAIL_SUBJECT__;
    }

    @Override
    public MappedEmailSubject as(String alias) {
        return new MappedEmailSubject(DSL.name(alias), this);
    }

    @Override
    public MappedEmailSubject as(Name alias) {
        return new MappedEmailSubject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MappedEmailSubject rename(String name) {
        return new MappedEmailSubject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MappedEmailSubject rename(Name name) {
        return new MappedEmailSubject(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
