/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.MappedEmailRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MappedEmail extends TableImpl<MappedEmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mapped_email</code>
     */
    public static final MappedEmail MAPPED_EMAIL = new MappedEmail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MappedEmailRecord> getRecordType() {
        return MappedEmailRecord.class;
    }

    /**
     * The column <code>mapped_email.id</code>.
     */
    public final TableField<MappedEmailRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>mapped_email.subject</code>.
     */
    public final TableField<MappedEmailRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.VARCHAR(255), this, "");

    private MappedEmail(Name alias, Table<MappedEmailRecord> aliased) {
        this(alias, aliased, null);
    }

    private MappedEmail(Name alias, Table<MappedEmailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mapped_email</code> table reference
     */
    public MappedEmail(String alias) {
        this(DSL.name(alias), MAPPED_EMAIL);
    }

    /**
     * Create an aliased <code>mapped_email</code> table reference
     */
    public MappedEmail(Name alias) {
        this(alias, MAPPED_EMAIL);
    }

    /**
     * Create a <code>mapped_email</code> table reference
     */
    public MappedEmail() {
        this(DSL.name("mapped_email"), null);
    }

    public <O extends Record> MappedEmail(Table<O> child, ForeignKey<O, MappedEmailRecord> key) {
        super(child, key, MAPPED_EMAIL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<MappedEmailRecord> getPrimaryKey() {
        return Keys.MAPPED_EMAIL__;
    }

    @Override
    public MappedEmail as(String alias) {
        return new MappedEmail(DSL.name(alias), this);
    }

    @Override
    public MappedEmail as(Name alias) {
        return new MappedEmail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MappedEmail rename(String name) {
        return new MappedEmail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MappedEmail rename(Name name) {
        return new MappedEmail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
