/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.NonMappedEmailRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NonMappedEmail extends TableImpl<NonMappedEmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>non_mapped_email</code>
     */
    public static final NonMappedEmail NON_MAPPED_EMAIL = new NonMappedEmail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NonMappedEmailRecord> getRecordType() {
        return NonMappedEmailRecord.class;
    }

    /**
     * The column <code>non_mapped_email.id</code>.
     */
    public final TableField<NonMappedEmailRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>non_mapped_email.subject</code>.
     */
    public final TableField<NonMappedEmailRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>non_mapped_email.message_id</code>.
     */
    public final TableField<NonMappedEmailRecord, byte[]> MESSAGE_ID = createField(DSL.name("message_id"), SQLDataType.BLOB, this, "");

    private NonMappedEmail(Name alias, Table<NonMappedEmailRecord> aliased) {
        this(alias, aliased, null);
    }

    private NonMappedEmail(Name alias, Table<NonMappedEmailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>non_mapped_email</code> table reference
     */
    public NonMappedEmail(String alias) {
        this(DSL.name(alias), NON_MAPPED_EMAIL);
    }

    /**
     * Create an aliased <code>non_mapped_email</code> table reference
     */
    public NonMappedEmail(Name alias) {
        this(alias, NON_MAPPED_EMAIL);
    }

    /**
     * Create a <code>non_mapped_email</code> table reference
     */
    public NonMappedEmail() {
        this(DSL.name("non_mapped_email"), null);
    }

    public <O extends Record> NonMappedEmail(Table<O> child, ForeignKey<O, NonMappedEmailRecord> key) {
        super(child, key, NON_MAPPED_EMAIL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<NonMappedEmailRecord> getPrimaryKey() {
        return Keys.NON_MAPPED_EMAIL__;
    }

    @Override
    public NonMappedEmail as(String alias) {
        return new NonMappedEmail(DSL.name(alias), this);
    }

    @Override
    public NonMappedEmail as(Name alias) {
        return new NonMappedEmail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NonMappedEmail rename(String name) {
        return new NonMappedEmail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NonMappedEmail rename(Name name) {
        return new NonMappedEmail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
