/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.PersonSeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PersonSeq extends TableImpl<PersonSeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Person_SEQ</code>
     */
    public static final PersonSeq PERSON_SEQ = new PersonSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonSeqRecord> getRecordType() {
        return PersonSeqRecord.class;
    }

    /**
     * The column <code>Person_SEQ.next_val</code>.
     */
    public final TableField<PersonSeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private PersonSeq(Name alias, Table<PersonSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersonSeq(Name alias, Table<PersonSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Person_SEQ</code> table reference
     */
    public PersonSeq(String alias) {
        this(DSL.name(alias), PERSON_SEQ);
    }

    /**
     * Create an aliased <code>Person_SEQ</code> table reference
     */
    public PersonSeq(Name alias) {
        this(alias, PERSON_SEQ);
    }

    /**
     * Create a <code>Person_SEQ</code> table reference
     */
    public PersonSeq() {
        this(DSL.name("Person_SEQ"), null);
    }

    public <O extends Record> PersonSeq(Table<O> child, ForeignKey<O, PersonSeqRecord> key) {
        super(child, key, PERSON_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public PersonSeq as(String alias) {
        return new PersonSeq(DSL.name(alias), this);
    }

    @Override
    public PersonSeq as(Name alias) {
        return new PersonSeq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PersonSeq rename(String name) {
        return new PersonSeq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PersonSeq rename(Name name) {
        return new PersonSeq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
