/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.RankingSeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RankingSeq extends TableImpl<RankingSeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Ranking_SEQ</code>
     */
    public static final RankingSeq RANKING_SEQ = new RankingSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RankingSeqRecord> getRecordType() {
        return RankingSeqRecord.class;
    }

    /**
     * The column <code>Ranking_SEQ.next_val</code>.
     */
    public final TableField<RankingSeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private RankingSeq(Name alias, Table<RankingSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private RankingSeq(Name alias, Table<RankingSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Ranking_SEQ</code> table reference
     */
    public RankingSeq(String alias) {
        this(DSL.name(alias), RANKING_SEQ);
    }

    /**
     * Create an aliased <code>Ranking_SEQ</code> table reference
     */
    public RankingSeq(Name alias) {
        this(alias, RANKING_SEQ);
    }

    /**
     * Create a <code>Ranking_SEQ</code> table reference
     */
    public RankingSeq() {
        this(DSL.name("Ranking_SEQ"), null);
    }

    public <O extends Record> RankingSeq(Table<O> child, ForeignKey<O, RankingSeqRecord> key) {
        super(child, key, RANKING_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public RankingSeq as(String alias) {
        return new RankingSeq(DSL.name(alias), this);
    }

    @Override
    public RankingSeq as(Name alias) {
        return new RankingSeq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RankingSeq rename(String name) {
        return new RankingSeq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RankingSeq rename(Name name) {
        return new RankingSeq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
