/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.SeparatetableparentSeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SeparatetableparentSeq extends TableImpl<SeparatetableparentSeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SeparateTableParent_SEQ</code>
     */
    public static final SeparatetableparentSeq SEPARATETABLEPARENT_SEQ = new SeparatetableparentSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeparatetableparentSeqRecord> getRecordType() {
        return SeparatetableparentSeqRecord.class;
    }

    /**
     * The column <code>SeparateTableParent_SEQ.next_val</code>.
     */
    public final TableField<SeparatetableparentSeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private SeparatetableparentSeq(Name alias, Table<SeparatetableparentSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private SeparatetableparentSeq(Name alias, Table<SeparatetableparentSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SeparateTableParent_SEQ</code> table reference
     */
    public SeparatetableparentSeq(String alias) {
        this(DSL.name(alias), SEPARATETABLEPARENT_SEQ);
    }

    /**
     * Create an aliased <code>SeparateTableParent_SEQ</code> table reference
     */
    public SeparatetableparentSeq(Name alias) {
        this(alias, SEPARATETABLEPARENT_SEQ);
    }

    /**
     * Create a <code>SeparateTableParent_SEQ</code> table reference
     */
    public SeparatetableparentSeq() {
        this(DSL.name("SeparateTableParent_SEQ"), null);
    }

    public <O extends Record> SeparatetableparentSeq(Table<O> child, ForeignKey<O, SeparatetableparentSeqRecord> key) {
        super(child, key, SEPARATETABLEPARENT_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public SeparatetableparentSeq as(String alias) {
        return new SeparatetableparentSeq(DSL.name(alias), this);
    }

    @Override
    public SeparatetableparentSeq as(Name alias) {
        return new SeparatetableparentSeq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeparatetableparentSeq rename(String name) {
        return new SeparatetableparentSeq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeparatetableparentSeq rename(Name name) {
        return new SeparatetableparentSeq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
