/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.SingletableparentSeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SingletableparentSeq extends TableImpl<SingletableparentSeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SingleTableParent_SEQ</code>
     */
    public static final SingletableparentSeq SINGLETABLEPARENT_SEQ = new SingletableparentSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SingletableparentSeqRecord> getRecordType() {
        return SingletableparentSeqRecord.class;
    }

    /**
     * The column <code>SingleTableParent_SEQ.next_val</code>.
     */
    public final TableField<SingletableparentSeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private SingletableparentSeq(Name alias, Table<SingletableparentSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private SingletableparentSeq(Name alias, Table<SingletableparentSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SingleTableParent_SEQ</code> table reference
     */
    public SingletableparentSeq(String alias) {
        this(DSL.name(alias), SINGLETABLEPARENT_SEQ);
    }

    /**
     * Create an aliased <code>SingleTableParent_SEQ</code> table reference
     */
    public SingletableparentSeq(Name alias) {
        this(alias, SINGLETABLEPARENT_SEQ);
    }

    /**
     * Create a <code>SingleTableParent_SEQ</code> table reference
     */
    public SingletableparentSeq() {
        this(DSL.name("SingleTableParent_SEQ"), null);
    }

    public <O extends Record> SingletableparentSeq(Table<O> child, ForeignKey<O, SingletableparentSeqRecord> key) {
        super(child, key, SINGLETABLEPARENT_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public SingletableparentSeq as(String alias) {
        return new SingletableparentSeq(DSL.name(alias), this);
    }

    @Override
    public SingletableparentSeq as(Name alias) {
        return new SingletableparentSeq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SingletableparentSeq rename(String name) {
        return new SingletableparentSeq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SingletableparentSeq rename(Name name) {
        return new SingletableparentSeq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
