/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.Keys;
import my.playground.orm.thirdtry.tables.records.SkillRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Skill extends TableImpl<SkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Skill</code>
     */
    public static final Skill SKILL = new Skill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SkillRecord> getRecordType() {
        return SkillRecord.class;
    }

    /**
     * The column <code>Skill.id</code>.
     */
    public final TableField<SkillRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>Skill.name</code>.
     */
    public final TableField<SkillRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private Skill(Name alias, Table<SkillRecord> aliased) {
        this(alias, aliased, null);
    }

    private Skill(Name alias, Table<SkillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Skill</code> table reference
     */
    public Skill(String alias) {
        this(DSL.name(alias), SKILL);
    }

    /**
     * Create an aliased <code>Skill</code> table reference
     */
    public Skill(Name alias) {
        this(alias, SKILL);
    }

    /**
     * Create a <code>Skill</code> table reference
     */
    public Skill() {
        this(DSL.name("Skill"), null);
    }

    public <O extends Record> Skill(Table<O> child, ForeignKey<O, SkillRecord> key) {
        super(child, key, SKILL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SkillRecord> getPrimaryKey() {
        return Keys.SKILL__;
    }

    @Override
    public Skill as(String alias) {
        return new Skill(DSL.name(alias), this);
    }

    @Override
    public Skill as(Name alias) {
        return new Skill(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Skill rename(String name) {
        return new Skill(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Skill rename(Name name) {
        return new Skill(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
