/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry.tables;


import my.playground.orm.thirdtry.DefaultSchema;
import my.playground.orm.thirdtry.tables.records.SkillSeqRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SkillSeq extends TableImpl<SkillSeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Skill_SEQ</code>
     */
    public static final SkillSeq SKILL_SEQ = new SkillSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SkillSeqRecord> getRecordType() {
        return SkillSeqRecord.class;
    }

    /**
     * The column <code>Skill_SEQ.next_val</code>.
     */
    public final TableField<SkillSeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private SkillSeq(Name alias, Table<SkillSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private SkillSeq(Name alias, Table<SkillSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Skill_SEQ</code> table reference
     */
    public SkillSeq(String alias) {
        this(DSL.name(alias), SKILL_SEQ);
    }

    /**
     * Create an aliased <code>Skill_SEQ</code> table reference
     */
    public SkillSeq(Name alias) {
        this(alias, SKILL_SEQ);
    }

    /**
     * Create a <code>Skill_SEQ</code> table reference
     */
    public SkillSeq() {
        this(DSL.name("Skill_SEQ"), null);
    }

    public <O extends Record> SkillSeq(Table<O> child, ForeignKey<O, SkillSeqRecord> key) {
        super(child, key, SKILL_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public SkillSeq as(String alias) {
        return new SkillSeq(DSL.name(alias), this);
    }

    @Override
    public SkillSeq as(Name alias) {
        return new SkillSeq(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SkillSeq rename(String name) {
        return new SkillSeq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SkillSeq rename(Name name) {
        return new SkillSeq(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
