/*
 * This file is generated by jOOQ.
 */
package my.playground.orm.thirdtry;


import my.playground.orm.thirdtry.tables.*;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>Ent1</code>.
     */
    public static final Ent1 ENT1 = Ent1.ENT1;

    /**
     * The table <code>Ent1_SEQ</code>.
     */
    public static final Ent1Seq ENT1_SEQ = Ent1Seq.ENT1_SEQ;

    /**
     * The table <code>Ent2</code>.
     */
    public static final Ent2 ENT2 = Ent2.ENT2;

    /**
     * The table <code>Ent2_SEQ</code>.
     */
    public static final Ent2Seq ENT2_SEQ = Ent2Seq.ENT2_SEQ;

    /**
     * The table <code>Ent3</code>.
     */
    public static final Ent3 ENT3 = Ent3.ENT3;

    /**
     * The table <code>Ent3_SEQ</code>.
     */
    public static final Ent3Seq ENT3_SEQ = Ent3Seq.ENT3_SEQ;

    /**
     * The table <code>JoinTableInheritor</code>.
     */
    public static final Jointableinheritor JOINTABLEINHERITOR = Jointableinheritor.JOINTABLEINHERITOR;

    /**
     * The table <code>JoinTableParent</code>.
     */
    public static final Jointableparent JOINTABLEPARENT = Jointableparent.JOINTABLEPARENT;

    /**
     * The table <code>JoinTableParent_SEQ</code>.
     */
    public static final JointableparentSeq JOINTABLEPARENT_SEQ = JointableparentSeq.JOINTABLEPARENT_SEQ;

    /**
     * The table <code>mapped_email</code>.
     */
    public static final MappedEmail MAPPED_EMAIL = MappedEmail.MAPPED_EMAIL;

    /**
     * The table <code>mapped_email_eager</code>.
     */
    public static final MappedEmailEager MAPPED_EMAIL_EAGER = MappedEmailEager.MAPPED_EMAIL_EAGER;

    /**
     * The table <code>mapped_email_subject</code>.
     */
    public static final MappedEmailSubject MAPPED_EMAIL_SUBJECT = MappedEmailSubject.MAPPED_EMAIL_SUBJECT;

    /**
     * The table <code>mapped_message</code>.
     */
    public static final MappedMessage MAPPED_MESSAGE = MappedMessage.MAPPED_MESSAGE;

    /**
     * The table <code>mapped_message_content</code>.
     */
    public static final MappedMessageContent MAPPED_MESSAGE_CONTENT = MappedMessageContent.MAPPED_MESSAGE_CONTENT;

    /**
     * The table <code>mapped_message_eager</code>.
     */
    public static final MappedMessageEager MAPPED_MESSAGE_EAGER = MappedMessageEager.MAPPED_MESSAGE_EAGER;

    /**
     * The table <code>non_mapped_email</code>.
     */
    public static final NonMappedEmail NON_MAPPED_EMAIL = NonMappedEmail.NON_MAPPED_EMAIL;

    /**
     * The table <code>non_mapped_message</code>.
     */
    public static final NonMappedMessage NON_MAPPED_MESSAGE = NonMappedMessage.NON_MAPPED_MESSAGE;

    /**
     * The table <code>Person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>Person_SEQ</code>.
     */
    public static final PersonSeq PERSON_SEQ = PersonSeq.PERSON_SEQ;

    /**
     * The table <code>Ranking</code>.
     */
    public static final Ranking RANKING = Ranking.RANKING;

    /**
     * The table <code>Ranking_SEQ</code>.
     */
    public static final RankingSeq RANKING_SEQ = RankingSeq.RANKING_SEQ;

    /**
     * The table <code>SeparateTableInheritor</code>.
     */
    public static final Separatetableinheritor SEPARATETABLEINHERITOR = Separatetableinheritor.SEPARATETABLEINHERITOR;

    /**
     * The table <code>SeparateTableParent</code>.
     */
    public static final Separatetableparent SEPARATETABLEPARENT = Separatetableparent.SEPARATETABLEPARENT;

    /**
     * The table <code>SeparateTableParent_SEQ</code>.
     */
    public static final SeparatetableparentSeq SEPARATETABLEPARENT_SEQ = SeparatetableparentSeq.SEPARATETABLEPARENT_SEQ;

    /**
     * The table <code>SingleTableParent</code>.
     */
    public static final Singletableparent SINGLETABLEPARENT = Singletableparent.SINGLETABLEPARENT;

    /**
     * The table <code>SingleTableParent_SEQ</code>.
     */
    public static final SingletableparentSeq SINGLETABLEPARENT_SEQ = SingletableparentSeq.SINGLETABLEPARENT_SEQ;

    /**
     * The table <code>Skill</code>.
     */
    public static final Skill SKILL = Skill.SKILL;

    /**
     * The table <code>Skill_SEQ</code>.
     */
    public static final SkillSeq SKILL_SEQ = SkillSeq.SKILL_SEQ;
}
